version: '3.5'

services:

  wordpress:
    container_name: wordpress_app
    build: ./
    restart: always
    ports:
        - 8080:80
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
        - ./app:/var/www/html
    networks:
        - wordpress

  db:
    container_name: wordpress_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
        - db:/var/lib/mysql
    networks:
        - wordpress

volumes:
  db:
  
networks: 
    wordpress: